### PR TITLE
Removes MSG_DONTROUTE flag from socket_sendto call

### LINKED ISSUE #2: Sending Magic Packet to Broadcast
Hi @tomnomnom 

Thanks for your work, like your package so far 👍 

I have a question about this line: https://github.com/tomnomnom/phpwol/blob/master/Phpwol/Socket.php#L12

What's the reason you're setting the `MSG_DONTROUTE` flag?
That's what preventing me from sending the magic packet to 255.255.255.255. It works after changing the flag to `0`.

Regards

### PR DESCRIPTION
**Pull request by strebl**
That enables us to send the magic packet to 255.255.255.255.

Fixes #2.

### CODE REVIEW

**Comment by tomnomnom** [comment]
Thanks! :)

**Comment by strebl** [comment]
Holy, that was fast 😄

**Comment by strebl** [comment]
Would be nice if you can create a new release soon 👍

**Comment by tomnomnom** [comment]
Done :)

**Comment by strebl** [comment]
Thanks @tomnomnom 😁

**Pull request merged**
